### ISSUE TITLE
Change order of home page gallery.

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Cleaning-Service-Site#2]
Cange order and switch gallery_image12 with gallery_image2

The next picture should be top row in the middle. 
![image](https://user-images.githubusercontent.com/26923359/27288466-7af2afea-550f-11e7-9c49-3ea80d5d09f6.png)

**Comment by iliyaM** [comment]
Added OrderBy text id on the code. 
I am afraid to deploy this site. its too old. 
@MeanEYE

**Comment by MeanEYE** [comment]
Okay @iliyaM. Close the issue, I'll deploy.
