### ISSUE TITLE
Update order.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Cleaning-Service-Site#5]
@iliyaM you said you added order numbers as `text_id`. This should be applied online as well.

**Comment by iliyaM** [comment]
Can i specify number 10 in text id on only one image and it will make it fist? or give everything else a bigger number?

**Comment by MeanEYE** [comment]
Easily tested and does not warrant this question.

**Comment by iliyaM** [comment]
It was tested with failed result. hence the question.

**Comment by iliyaM** [comment]
@talovdat 
ordering work with text_id = '01' or '02' '03' '10' '11'...etc
